### ISSUE TITLE
How to train or validate a model from scratch？

### ISSUE THREAD

**Issue by JC0624** [ruiking04/COCA#1]
Sorry, I would like to ask how to start training a model. I can't get more information from the README.

**Comment by ruiking04** [comment]
Our paper has been updated and we will update the code soon.

**Comment by JC0624** [comment]
> 我们的论文已经更新，我们将很快更新代码。

Thanks for your reply, I look forward to updating your code.

**Comment by JC0624** [comment]
> Our paper has been updated and we will update the code soon.

Thanks for your reply, I look forward to your updated code.

**Comment by ruiking04** [comment]
Thank you for following our work.
I have updated the code and paper, you can train the COCA model.

**Comment by JC0624** [comment]
> 感谢您关注我们的工作。我已经更新了代码和论文，可以训练COCA模型。

Sincerely thank you for your reply and attention! I wish you success in your work！

**Comment by 943fansi** [comment]
@JC0624 老哥，代码你跑通了吗，结果怎样

**Comment by wr330** [comment]
> @JC0624 老哥，代码你跑通了吗，结果怎样
He has run the COCA.
See Links: [issue 2](https://github.com/ruiking04/COCA/issues/2)

**Comment by 943fansi** [comment]
@wr330 Thank you. Have you tried running the code, and what were the results of the reproduction?

**Comment by wr330** [comment]
I've run the code.
The results are good and similar to those reported in the paper. [COCA](https://arxiv.org/abs/2207.01472)

**Comment by 943fansi** [comment]
@wr330 final results you got?

**Comment by wr330** [comment]
![image](https://user-images.githubusercontent.com/16575928/206705551-4fa02740-5ac9-4030-917f-29b05b49ba70.png)

**Comment by 943fansi** [comment]
@wr330 Thank you for sharing. Is this running 5 times with the same parameters? Each training takes 6 hours, which looks time-consuming. How large is your training set, and are you using a GPU?

**Comment by wr330** [comment]
> @wr330 Thank you for sharing. Is this running 5 times with the same parameters? Each training takes 6 hours, which looks time-consuming. How large is your training set, and are you using a GPU?

Yes, different random seeds. I was running 5 random seeds simultaneously in parallel on GPU: NVIDIA TESLA V100. There is quite a lot of data in the UCR. I was ready to do Baseline and ran something else. And I think the reason for the long run time is that the LSTM runs serially. It's faster if changes to GRU.
