### ISSUE TITLE
baseline.py - append

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#10]
Hello,

I am having troubles with baseline.py. I did the following replacements and the code runs:

            changed from: ts_df = train_scores.to_pd().append(test_scores.to_pd())
            changed to:     ts_df = pd.concat([train_scores.to_pd(), test_scores.to_pd()], ignore_index=True)

            changed from: df.append(ts_df, ignore_index=True)
            changed to:     df = pd.concat([df, ts_df], ignore_index=True)

I also did configuration involving Java and py4j. The code seems to run okay without errors.

However, in regards to the results, when I do IsolationForest, all my results are zero. I am using 17 custom datasets that were derived following the UCR datasets. I don't know why the results are zero and if this is an okay results.

Please let me know how I could correct this.

Thanks,
Marcia

**Comment by ruiking04** [comment]
Hello,

I see no problem with your code. "baseline.py" mainly calls the Merlion library.
I suspect that IsolationForest's anomaly detection performance is not good. I would suggest running all 250 datasets from UCR to see if there are any good subsets.

Best regards,
Rui

**Comment by marciahon29** [comment]
Hello,

I have been able to get results with IsolationForest. What I did was do everything from scratch (using all as is downloaded from your github).

Marcia
