### ISSUE TITLE
TS_TCC - Anomaly Detection

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#11]
Hello,

I am working on ts_tcc_main.py file. I try to run the "Anomaly Detection" option with my dataset and I get the following error:

Traceback (most recent call last):
  File ".../COCA-main/./ts_tcc_main.py", line 120, in <module>
    chkpoint = torch.load(os.path.join(load_from, "ckp_last.pt"), map_location=device)
  File "../Jupy_ENV/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File ".../Jupy_ENV/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "../Jupy_ENV/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'experiments_logs/Exp2/run1/self_supervised_seed_5/UCR/_0/saved_models/ckp_last.pt'

I checked the ".../COCA-main/experiments_logs/Exp2/run1/self_supervised_seed_5/" folder and it does not have "UCR/_0/saved_models/ckp_last.pt".

Please let me know how I could correct this.

Thanks,
Marcia

**Comment by ruiking04** [comment]
Hello,

TS-TCC is a two-stage model that first requires a self-supervised training model followed by anomaly detection. That is, first "--training_mode= self_supervised", and then "--training_mode= anomaly_detection" after it is finished.
The model file under this path "UCR/_0/saved_models/ckp_last.pt" is the model obtained from the self-supervised training.

Best regards,
Rui

**Comment by marciahon29** [comment]
Thank you!

**Comment by marciahon29** [comment]
Thank you!
