### ISSUE TITLE
Results of baseline.py are all the same

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#13]
Hello,

Please could you give me any insight as to why Accuracy, Precision, and Recall are all the same for the different models as per below (from log.txt). I don't know why this is happening. I did not change the code much.

['IsolationForest'] UCR Reasonable Metrics
['IsolationForest'] UCR  {'accuracy': 0.9411764705882353}
['IsolationForest'] UCR Affiliation Metrics
['IsolationForest'] UCR  {'precision': 0.00011550719361908644, 'recall': 0.007922012085960176}
['RandomCutForest'] UCR Reasonable Metrics
['RandomCutForest'] UCR  {'accuracy': 0.9411764705882353}
['RandomCutForest'] UCR Affiliation Metrics
['RandomCutForest'] UCR  {'precision': 0.00011550719361908644, 'recall': 0.007922012085960176}
['SpectralResidual'] UCR Reasonable Metrics
['SpectralResidual'] UCR  {'accuracy': 0.9411764705882353}
['SpectralResidual'] UCR Affiliation Metrics
['SpectralResidual'] UCR  {'precision': 0.00011550719361908644, 'recall': 0.007922012085960176}
['LSTMED'] UCR Reasonable Metrics
['LSTMED'] UCR  {'accuracy': 0.9411764705882353}
['LSTMED'] UCR Affiliation Metrics
['LSTMED'] UCR  {'precision': 0.00011550719361908644, 'recall': 0.007922012085960176}
['DAGMM'] UCR Reasonable Metrics
['DAGMM'] UCR  {'accuracy': 0.9411764705882353}
['DAGMM'] UCR Affiliation Metrics
['DAGMM'] UCR  {'precision': 0.00011550719361908644, 'recall': 0.007922012085960176}
['CPC'] UCR Reasonable Metrics
['CPC'] UCR  {'accuracy': 0.9411764705882353}
['CPC'] UCR Affiliation Metrics
['CPC'] UCR  {'precision': 0.00011550719361908644, 'recall': 0.007922012085960176}
['OCSVM'] UCR Reasonable Metrics
['OCSVM'] UCR  {'accuracy': 0.9411764705882353}
['OCSVM'] UCR Affiliation Metrics
['OCSVM'] UCR  {'precision': 0.00011550719361908644, 'recall': 0.007922012085960176}

**Comment by ruiking04** [comment]
Hello,

This one could be an error in our code, the log.txt is filled with the same result. I have two questions to confirm.
1) Your log.txt contains the result of many methods, how did this run baseline.py to get?
2) There should be a csv file under this path "summary = os.path.join("results", "anomaly", f"{dataset_to_name(dataset)}_summary. csv")" that What are the results?

![image](https://github.com/ruiking04/COCA/assets/98844439/bca290c8-fc5f-4267-a32a-66da3c5b9ab0)

**Comment by marciahon29** [comment]
My results for IsolationForest are very close to yours.
