### ISSUE TITLE
Table 2 - Calculating the Standard Deviation

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#14]
Hello,

In Table 2 of yor paper, you have "Affiliation F1" and "Accuracy".

I would like to ask you how do you determine what the standard deviation is?

For example, in COCA's Accuracy is 66.12 +- 2.62 and COCA's Affiliation F1 is 79.15 +- 1.27 .

How do you calculate "2.62" and "1.27"?

Thanks,
Marcia

**Comment by ruiking04** [comment]
Hello,

Choose a different random seed and then there will be different results. For example, in coca.py, the random seed is set as follows:
![image](https://github.com/ruiking04/COCA/assets/98844439/ae8e86cc-285a-407e-82cb-8bc87d6abb3c)

**Comment by marciahon29** [comment]
Hello,

Sorry, I do not understand how changing the seed gets the standard
deviation.

Please could provide clearer calculations.

Thanks

**Comment by ruiking04** [comment]
Hello,

This requires running the model with different seeds, then getting the results, and then calculating it yourself.
Taking COCA as an example,
seed=1,  F1=0.45
seed=2,  F1=0.36
seed=3,  F1=0.50
......
seed=n, F1=0.60
The mean of F1 is：
mu = 1/n *（F1(seed=1) + F1(seed=2) + F1(seed=3) + ……+F1(seed=n)）
standard deviation see：
[standard deviation](https://en.wikipedia.org/wiki/Standard_deviation)

**Comment by marciahon29** [comment]
Hello,

Where do I change the seed? Also, what is the number of times seed should be used? 5/10 times?

Also, In Table 2, you calculate "Affiliation F1". Please could you let me know how you calculated this?

Thanks,
Marcia

**Comment by marciahon29** [comment]
How do I set the seed for this command: python baseline.py --dataset UCR --model <model_name>  --debug ?

**Comment by ruiking04** [comment]
baseline.py is based on the Salesforce-Merlion library. The method in baseline.py does not have a fixed random seed, so the results of methods based on deep models are generally different each time.

**Comment by marciahon29** [comment]
How many times do you run a model in order to determine the standard deviation? Also, how do you calculate the "F1Score"?
