### ISSUE TITLE
Baseline.py - Getting Zeros

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#15]
Hello,

My Baseline models are all getting results of zero.

Please could you let me know in which file the results are stored.

I'm thinking that I am looking at the wrong file since I almost did not change the code at all and I am using the original UCR dataset.

Thanks,
Marcia

**Comment by ruiking04** [comment]
Hello,

There should be a CSV file at the path “./results/anomaly/xxx_summary.csv”. 
What is its result?

In baseline.py, the above code is as follows：
![image](https://github.com/ruiking04/COCA/assets/98844439/5958517e-cff2-4c95-8358-23628531cf66)

**Comment by ruiking04** [comment]
Take the isolated forest as an example:
There is an "IOpsCompetition_summary" file under the path "./results/anomaly".

I guess there is something wrong with the following code in baseline.py. Merlion first generates the CSV file (./results/anomaly/IsolationForest) of each time-series point prediction and then post-processes it.

![image](https://github.com/ruiking04/COCA/assets/98844439/7f49f906-340d-4ea3-a95e-dd956c07a4ee)

**Comment by marciahon29** [comment]
I get the file : UCR_summary.csv in the folder results/anomaly.

The contents are all zero.

I don't know why this is so. Would you have some experience with this?

**Comment by ruiking04** [comment]
I tried the source code and found no problem. The result is as follows:

![image](https://github.com/ruiking04/COCA/assets/98844439/6d514ec4-b0f4-4bbb-b9bb-4688e4509b3a)
![image](https://github.com/ruiking04/COCA/assets/98844439/b954f8a2-d7c7-4625-8283-8b4abf7d7944)

Experimental setup：
model=IsolationForest
dataset=UCR

I suggest you try it with the IOpsCompetition dataset first. Whether its result is 0.
I guess you may not have downloaded the UCR data set, or you may not have decompressed it correctly.

**Comment by marciahon29** [comment]
Please could you upload the baseline.py file you are using?

**Comment by marciahon29** [comment]
Please could you also provide the script for IsolationForest?

**Comment by ruiking04** [comment]
The baseline.py I used is the same as the code in the GitHub repository. The link is as follows:
[baseline](https://github.com/ruiking04/COCA/blob/main/baseline.py)
The source code implementation of the isolated forest references the Merlion library:
[IsolationForest](https://github.com/salesforce/Merlion/blob/main/merlion/models/anomaly/isolation_forest.py)

**Comment by marciahon29** [comment]
I redid everything from scratch and baseline.py appears to be working.
