### ISSUE TITLE
Merlion folders

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#17]
I downloaded the project from scratch and did all the processes detailed in GitHub.

However, I keep getting these messages that it does not recognize "merlion.*". I changed everything to "Merlion.merlion.*" but this also gave me problems. An error message is as below:

Traceback (most recent call last):
  File "coca.py", line 7, in <module>
    from models.TS_TCC.TS_utils import _logger
  File "...\COCA-main\models\__init__.py", line 1, in <module>
    from .OCSVM import OCSVMConf, OCSVM
  File "...\COCA-main\models\OCSVM\__init__.py", line 1, in <module>
    from .DetectorConfig import OCSVMConf
  File "...\COCA-main\models\OCSVM\DetectorConfig.py", line 1, in <module>
    from merlion.models.anomaly.base import DetectorConfig
ModuleNotFoundError: No module named 'merlion.models'

Please share with me your experience with this.

Thanks,
Marcia

**Comment by ruiking04** [comment]
We are sorry. During the process of re-downloading and running, some bugs appeared and have been modified. (See [update](https://github.com/ruiking04/COCA/commits/main/) ）

But your problem didn't occur.

run "coca.py"
![image](https://github.com/ruiking04/COCA/assets/98844439/635e2b05-c6ea-49b1-80be-ccdb0c48b214)
run "baseline.py"
![image](https://github.com/ruiking04/COCA/assets/98844439/329e4c28-3824-4f3d-a918-e5d9621c8203)

The dependent libraries are as shown below: 
![image](https://github.com/ruiking04/COCA/assets/98844439/c36a914c-38d7-4e4f-8f6a-b1870aa57c87)
salesforce-merlion==1.1.1

May I ask, can coca.py run normally? We guess it is an environmental problem, especially the configuration of the “salesforce-merlion” environment.

**Comment by marciahon29** [comment]
It was an environmental error. Thanks
