### ISSUE TITLE
TS_TCC Error

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#18]
Hello,

When trying to run TS_TCC (Self Supervised), I get this error:

Traceback (most recent call last):
  File "./ts_tcc_main.py", line 197, in <module>
    train_dl, valid_dl, test_dl = data_generator1(time_series, time_series_label, configs, training_mode)
  File ".../COCA-main/models/TS_TCC/dataloader/dataset.py", line 107, in data_generator1
    train_dataset = Load_Dataset(train_dat_dict, configs, training_mode)
  File ".../COCA-main/models/TS_TCC/dataloader/dataset.py", line 37, in __init__
    self.aug1, self.aug2 = DataTransform(self.x_data, config)
  File ".../COCA-main/models/TS_TCC/dataloader/augmentations.py", line 8, in DataTransform
    strong_aug = jitter(permutation(sample, max_segments=config.augmentation.max_seg), config.augmentation.jitter_ratio)
  File ".../COCA-main-December182023/COCA-main/models/TS_TCC/dataloader/augmentations.py", line 42, in permutation
    warp = np.concatenate(np.random.permutation(splits)).ravel()
  File "mtrand.pyx", line 4703, in numpy.random.mtrand.RandomState.permutation
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (
7,) + inhomogeneous part.

Plesae could you let me know how you solved this?

Thanks,
Marcia

**Comment by marciahon29** [comment]
Please could you also let me know where the results for TS_TCC is located?

**Comment by marciahon29** [comment]
I solved with this:

            permutated_splits = [np.random.permutation(split) for split in splits]
            warp = np.concatenate(permutated_splits).ravel()

I don't know if it is correct solution.

**Comment by ruiking04** [comment]
TS_TCC is a two-stage method. Self-supervised will generate a pre-trained model. The path is: “experiments_logs/Exp2/run1/self_supervised_seed_7/UCR/_0/saved_models/ckp_last.pt”.

```
            permutated_splits = [np.random.permutation(split) for split in splits]
            warp = np.concatenate(permutated_splits).ravel()

```
The above code is correct.

**Comment by marciahon29** [comment]
Thank you, it works!
