### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by JC0624** [ruiking04/COCA#2]
Hello, I follow the command provided in your readme: python coca py --selected_ Dataset UCR -- device cuda -- seed 2, but the following results are obtained. How can I solve this problem?
![Snipaste_2022-11-20_14-23-54](https://user-images.githubusercontent.com/64187594/202888965-534a9efd-bf3d-446b-ad68-66a84b7e344c.png)

**Comment by ruiking04** [comment]
The code "ucr.py"  of merlion's data loading package "ts_datasets.ts_datasets.anomaly" has been fixed.
The reason is that the data loading path is incorrect.

**Comment by JC0624** [comment]
> The code "ucr.py" of merlion's data loading package "ts_datasets.ts_datasets.anomaly" has been fixed. The reason is that the data loading path is incorrect.

Thank you for your help! I downloaded your project again, and now it can run normally.Thanks again for your help!

**Comment by ruiking04** [comment]
Thank you for your interest in our work
