### ISSUE TITLE
Figure 3

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#23]
Hello,

Please could you let me know where in the code you create "Figure 3 - AD results of COCA on AIOps and UCR".

Thanks

**Comment by ruiking04** [comment]
Modify a parameter in coca.py and there will be a picture.

https://github.com/ruiking04/COCA/blob/main/coca.py 30~31
```
parser.add_argument('--visualization', default=True, type=bool,
                    help='Visualize')
```
