### ISSUE TITLE
Hyperparameters Search

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#24]
Hello,

You suggested to play with: window_size, time_step, batch_size, scale_ratio, and jitter_ratio. Should I try other variables too?

I would like to ask you what is acceptable ranges for each of the above values.

I would also like to know how they are related to each other. For example, I believe that window_size must be proportional to batch_size.

Thanks,
Marcia

**Comment by ruiking04** [comment]
window_size：16,32,64,128
time_step： 1,2,4,8,16,32
batch_size：256，512, 1024
sacle_ratio: 0.6, 0.7,0.8,0.9,1.0,1.1,1.2,1.3
self.jitter_ratio: 0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5

**Comment by marciahon29** [comment]
How about for time_step and batch_size? are they calculated based on other variables? how do these work?

**Comment by marciahon29** [comment]
I get an error message about "mat1 and mad2 shapes cannot be multiplied (1536x2176 and 1152x576)..."

I *believe* the issue is that a certain window_size can only be accomplished with a specific time_step and batch_size. 

Please could you let me know the relations between window_size/time_step/batch_size?

scale_ratio and jitter_ratio are working fine.

**Comment by marciahon29** [comment]
Additionally, you have a variable called "feature_len". What is this variable? Is it the number of features from the dataset? For example, the features for electricity consumption include "3" such as "temperature", "hour", and "location". So, would this be a feature_len of 3?

**Comment by marciahon29** [comment]
Did you also tweak other variables?

input_channels
kernel_size
stride
final_out_channels
hidden_size
num_layers
project_channels
dropout
features_len
window_size
time_step
num_epoch
freeze_length_epoch
change_center_epoch
center_eps
omega1
omega2
beta1
beta2
lr
drop_last
batch_size
nu
detect_nu
threshold_determine
objective
loss_type
scale_ratio
jitter_ratio

**Comment by marciahon29** [comment]
Thank you, I was able to do a randomized search based on the parameters you suggested.
