### ISSUE TITLE
Result error

### ISSUE THREAD

**Issue by JC0624** [ruiking04/COCA#3]
Hello, when I run the model according to the default command your readme, the result is always 0. How should I solve the problem?
![image](https://user-images.githubusercontent.com/64187594/224336070-2fb441c0-847b-4ff9-9f5b-7c3f0ef2cb30.png)

**Comment by JC0624** [comment]
I'm sorry it was my problem, the values of the model are now normal.

**Comment by secretfish2000** [comment]
I have the same problem as you，how do you solve the problem?

**Comment by ruiking04** [comment]
Are all evaluation metrics zero?
If not, then change the hyperparameters. We recommend that d first run first use the m default hyperparameters.

**Comment by secretfish2000** [comment]
![QQ截图20230425175238](https://user-images.githubusercontent.com/113569100/234241198-9ee5de67-6cb9-4936-a259-3d4e78bad0f6.png)
The result is as shown in the figure, only two items are not 0, I did not change the parameters. Is this the right result

**Comment by ruiking04** [comment]
I presume that you are using the UCR dataset.
It contains 250 time-series sub-datasets. Each sub-dataset contains only one anomaly segment in the test and trains one model.
So one of the sub-datasets is likely to show 0 for some metrics. Our program is run on 250 sub-datasets and then they are evaluated as a whole.

**Comment by ruiking04** [comment]
One more word, we have been disagreeing with the practice of some papers that use only a few subsets of time-series datasets, adjusting the hyperparameters separately. Finally, claim that they used these datasets.
This is not fair.

**Comment by secretfish2000** [comment]
Thank you for your prompt reply! I do use URC dataset. Interested in your article, so I also have two more questions:
1.In models/COCA/coca_network/model.py 
Detailed at line 91 and 93, why the rec_project doesn't use dec_hidden(the result of self.decoder). It doesn't fit with your model architecture.
2.The question of set self.center_eps = 0.1(UCR_Configs.py). In the process of finding the center C, as shown in the figure below, the result above is the real center of the circle (without eps), and the result below after eps, all the results become +-0.1. So is this parameter and result correct？And I'm not sure if it's the right process to feed data into an untrained model to find the center C.
Thanks & Regards！
![QQ截图20230425211219](https://user-images.githubusercontent.com/113569100/234287782-1c194203-f56b-4885-b941-341d384b7aa5.png)

**Comment by ruiking04** [comment]
Thanks for your interest in our work.
1. This is the “teacher-force” technique in the reconstruction method/Seq2Seq, and there are many instructions online. Merlion has a similar source code, link: [LSTM_ED](https://github.com/salesforce/Merlion/blob/main/merlion/models/anomaly/lstm_ed.py)
2. This “eps” setting is borrowed from [DeepSVDD.](https://github.com/lukasruff/Deep-SVDD-PyTorch). we also tried in our experiments that eps was not fixed, and as a result, the collapse occurred and the performance was not good.

**Comment by secretfish2000** [comment]
> Owner

Thanks for your replies.

**Comment by ruiking04** [comment]
Thanks.
