### ISSUE TITLE
关于标签预处理的疑问

### ISSUE THREAD

**Issue by fly-orange** [ruiking04/COCA#7]
作者你好，感谢提供源码！关于窗口异常标签有一个小疑问，为什么只需要考虑每个窗口的前configs.time_step个时刻，而不是用整个窗口内是否存在异常来衡量。
![image](https://github.com/ruiking04/COCA/assets/77927387/e9086277-c8d9-441f-a49e-bccf37e3f51c)

**Comment by ruiking04** [comment]
首先，谢谢关注我们的工作。这一块是因为，一条长的时间序列根据时间窗window_size和时间步Ts切割为N个样本，样本数量其实主要取决于Ts，如果按照整个窗口内是否存在异常来衡量，当window_size>Ts时，在长的时间序列的一个异常点，则有可能会产生很多异常样本，这样我们认为不是很公平。当然这一块没有定论，我们也看到“按照整个窗口内是否存在异常”的论文，但是这会使最后的效果偏高。还有一些论文会“按照整个窗口内是否存在异常”，再预测完成以后，再把一个个sample得到的异常分数恢复成一条长的时间异常分数序列，然后对于重复的部分异常分数取均值或者取效果最好的情况。

**Comment by fly-orange** [comment]
非常感谢您的及时回复！这种预处理可以理解为避免单点异常的多次重复标注。想问一下，为什么不采用时间窗内的最后ts个点，因为直观上我们还是希望更及时的发现异常，即最近几个点有无异常。为什么采用前ts个点呢，是考虑了异常事件对时间序列影响的滞后性吗，或者是出于其他特殊的考虑呢。

**Comment by ruiking04** [comment]
一个好的想法，我们当时按照时间的顺序，直观上选择了时间窗内的前ts个点，如果有兴趣可以选择时间窗内的最后ts个点，做一下实验，观察一下结果。

**Comment by fly-orange** [comment]
好的了解了，非常感谢您，很棒的工作！
