### ISSUE TITLE
data_generator4 - where is this?

### ISSUE THREAD

**Issue by marciahon29** [ruiking04/COCA#9]
Hello,

In both coca_no_var.py and coca_view.py, there is a reference to data_generator4 .

I searched in the folder "dataloader" and found data_generator1 and data_generator2.

Please could you let me know what I need to do to get data_generator4 to work?

Thanks,
Marcia

**Comment by ruiking04** [comment]
Thanks for your interest in our work.
It was our mistake. coca_no_var.py and coca_view.py should all be data_generator1. We've updated our code as well. 
Thanks again.

**Comment by marciahon29** [comment]
It works, thanks!

**Comment by marciahon29** [comment]
It works! Thanks!
